### PR TITLE
update tiramisu_core 

### PR DESCRIPTION
**Pull request by GueroudjiAmal**

### CODE REVIEW

**Comment by rbaghdadi** [comment]
The functions are already declared in src/tiramisu_function.cpp, why are you redefining them? Please fix them in src/tiramisu_function.cpp directly

**Comment by GueroudjiAmal** [comment]
they are defined in tiramisu_core not tiramisu_function

**Comment by rbaghdadi** [comment]
Aren't they defined here?

https://github.com/Tiramisu-Compiler/tiramisu/blob/3ec5251c55d1b37c83cdcb303b1b93b7d34270c3/src/tiramisu_function.cpp#L924

**Comment by GueroudjiAmal** [comment]
Il se trouve que chez moi elles sont déclaré dans tiramisu_core.cpp
et je ne me rappelle jamais les avoir déclaré dans tiramisu_function.
 là  j'arrive pas à envoyer a pull request, probleme de cnx, je le
ferai tt à l'heure

2019-03-11 18:01 UTC+01:00, Riyadh Baghdadi <notifications@github.com>:
> Aren't they defined here?
>
> https://github.com/Tiramisu-Compiler/tiramisu/blob/3ec5251c55d1b37c83cdcb303b1b93b7d34270c3/src/tiramisu_function.cpp#L924
>
>
>
>
>
> --
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/Tiramisu-Compiler/tiramisu/pull/185#issuecomment-471628838


-- 
GUEROUDJI Amal

**Pull request closed without merging**
