### PR TITLE
NN code

### PR DESCRIPTION
**Pull request by RadjaHachilif**

### CODE REVIEW

**Comment by rbaghdadi** [comment]
I see that you remove many files (for example you remove all of conv2), why is that?

**Comment by RadjaHachilif** [comment]
I apologize sir, my repository is kind of a mess right now. I'm trying to
go back to the original code as in master then add the new blocks before
sending a new pull request.

Le ven. 25 janv. 2019 à 23:17, Riyadh Baghdadi <notifications@github.com> a
écrit :

**Comment by rbaghdadi** [comment]
This is Ok, but I prefer that you close the pull request then, clean every thing and send a new pull request later.

**Comment by rbaghdadi** [comment]
If your branch is a mess as you said, better clone a fresh copy of from master and start moving your old code to it step by step. It would be ideal if you do a small change and change the pull request right away. I can't review a very large pull request.

**Pull request closed without merging**
